name: Pip Install
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  pip:
    container:
      image: python:3.9.5
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    name: Pip Install
    runs-on:
    - self-hosted
    - docker
    steps:
    - name: Install SSH client
      run: apt update && apt -y install openssh-client
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Install package
      run: pip install .
