name: Waf Python Tests
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request: null
jobs:
  waf:
    name: Linux Waf
    runs-on:
    - self-hosted
    - Linux
    - vagrant
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: python3 waf configure
    - name: Build
      run: python3 waf
    - name: Test
      run: python3 waf --run_tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
